### ISSUE TITLE
activity create bug

### ISSUE THREAD

**Issue by froststein** [AY2122S2-CS2113T-T10-1/tp#215]
Activity ID is being retrieved before arguments and fields are verified. This causes the system to increment the activity ID internally without assigning those ID to any activities. 

/p delimiter should check that only 1 name can appear, this section should be reflected on UG as well.

/p Alice /i Bob would generate an error where by Bob does not owe Alice anything

**Comment by warrencxw** [comment]
Latter resolved by #218
