### ISSUE TITLE
[Code review] @warrencxw

### ISSUE THREAD

**Issue by slewyh** [AY2122S2-CS2113T-T10-1/tp#442]
1.  You can leave out comments that explain _how_ the code works if it's self-explanatory. See [explain the what, why and not how](https://nus-cs2113-ay2122s2.github.io/website/se-book-adapted/chapters/codeQuality.html#explain-what-and-why-not-how).

![Screenshot 2022-04-05 at 11 02 26 AM](https://user-images.githubusercontent.com/43779956/161671257-8af7b2c3-3d60-4185-95ee-02e1d1792680.png)

2. `removeActivityList()` does two main things, remove the activities and their associated cost objects that are attached to Persons.
SLAP could be applied here with 2 abstracted methods .

![Screenshot 2022-04-05 at 11 03 51 AM](https://user-images.githubusercontent.com/43779956/161671588-aa8d1786-a58d-405a-b806-969ca7d7ec46.png)

**Comment by warrencxw** [comment]
@slewyh 
Thank you for your review.

With regards to part 1, I am explaining in the comments **what** the command arguments should be, they should be delimited by the delimiter. E.g. an expected input should be something that contains `/sid 4`, a string that contains both the delimiter and the argument itself from the user input.
I'm not sure where I may have actually explained how the code works at all, maybe it would be really great if you could clarify this.

With regards to part 2, I agree with that point and I will work on that part.

**Comment by slewyh** [comment]
1.  For this short method ,you can leave out the comments altogether. It is already captured in code:
line120 - _given_ command arguments 
line 122- _return_ integer with delimiter   

A more meaningful comment can be `extracts session id from user input`.
